#!/bin/bash
# 配置 genimg/genvideo 共用的 macOS 环境变量。

set -euo pipefail

genimg_service_name="genimg-api-key"
genimg_env_file="${HOME}/.genimg-env.zsh"
genimg_dry_run=0

genimg_usage() {
    cat <<'EOF'
用法：
  bash configure-macos.sh
  IMAGE_API_BASE=https://relay.example/v1 GENIMG_API_KEY=sk-xxx \
    bash configure-macos.sh --dry-run

配置项：
  IMAGE_API_BASE  中转站 OpenAI 兼容 API 地址，通常以 /v1 结尾
  GENIMG_API_KEY  中转站 API key；实际运行时存入 macOS Keychain

选项：
  --dry-run       只检查将要执行的操作，不写文件或 Keychain
  -h, --help      显示帮助
EOF
}

case "${1:-}" in
    --dry-run)
        genimg_dry_run=1
        ;;
    -h|--help)
        genimg_usage
        exit 0
        ;;
    "")
        ;;
    *)
        echo "未知参数: $1" >&2
        genimg_usage >&2
        exit 2
        ;;
esac

if [ "$(uname -s)" != "Darwin" ]; then
    echo "此脚本仅支持 macOS。" >&2
    exit 1
fi

if ! command -v security >/dev/null 2>&1; then
    echo "找不到 macOS security 命令，无法安全保存 API key。" >&2
    exit 1
fi

genimg_base_url="${IMAGE_API_BASE:-}"
if [ -z "$genimg_base_url" ]; then
    read -r -p "请输入图片/视频中转站地址（通常以 /v1 结尾）: " genimg_base_url
fi
if [ -z "$genimg_base_url" ]; then
    echo "IMAGE_API_BASE 不能为空。" >&2
    exit 1
fi
case "$genimg_base_url" in
    http://*|https://*)
        ;;
    *)
        echo "IMAGE_API_BASE 必须以 http:// 或 https:// 开头。" >&2
        exit 1
        ;;
esac
genimg_base_url="${genimg_base_url%/}"

genimg_api_key="${GENIMG_API_KEY:-}"
genimg_has_keychain_key=0
if [ -z "$genimg_api_key" ]; then
    if security find-generic-password -a "$USER" -s "$genimg_service_name" -w >/dev/null 2>&1; then
        genimg_has_keychain_key=1
    fi
fi

if [ -z "$genimg_api_key" ] && [ "$genimg_has_keychain_key" -eq 0 ]; then
    read -r -s -p "请输入 GENIMG_API_KEY（输入不会显示）: " genimg_api_key
    echo
fi
if [ -z "$genimg_api_key" ] && [ "$genimg_has_keychain_key" -eq 0 ]; then
    echo "GENIMG_API_KEY 不能为空。" >&2
    exit 1
fi

if [ "$genimg_dry_run" -eq 1 ]; then
    echo "dry-run："
    echo "  IMAGE_API_BASE=$genimg_base_url"
    echo "  GENIMG_API_KEY=已提供或已存在于 Keychain"
    echo "  Keychain service=$genimg_service_name"
    echo "  环境文件=$genimg_env_file"
    echo "  将更新=${HOME}/.zprofile, ${HOME}/.zshrc"
    exit 0
fi

if [ -n "$genimg_api_key" ]; then
    security add-generic-password \
        -U \
        -a "$USER" \
        -s "$genimg_service_name" \
        -w "$genimg_api_key" >/dev/null
fi

genimg_temp_file="$(mktemp "${TMPDIR:-/tmp}/genimg-env.XXXXXX")"
trap 'rm -f "$genimg_temp_file"' EXIT
umask 077
{
    echo "# Generated by Image-Gen/configure-macos.sh"
    printf 'export IMAGE_API_BASE=%q\n' "$genimg_base_url"
    printf '%s\n' 'export GENIMG_API_KEY="$(security find-generic-password -a "$USER" -s "genimg-api-key" -w 2>/dev/null)"'
} > "$genimg_temp_file"
mv "$genimg_temp_file" "$genimg_env_file"
chmod 600 "$genimg_env_file"
trap - EXIT

genimg_source_line='[ -r "$HOME/.genimg-env.zsh" ] && source "$HOME/.genimg-env.zsh"'
for genimg_profile in "${HOME}/.zprofile" "${HOME}/.zshrc"; do
    touch "$genimg_profile"
    if ! grep -Fq "$genimg_source_line" "$genimg_profile"; then
        {
            echo
            echo "# genimg banana/image2 environment"
            echo "$genimg_source_line"
        } >> "$genimg_profile"
    fi
done

if [ -z "$genimg_api_key" ]; then
    genimg_api_key="$(security find-generic-password -a "$USER" -s "$genimg_service_name" -w)"
fi

genimg_script_dir="$(cd "$(dirname "$0")" && pwd)"
if command -v python3 >/dev/null 2>&1 && [ -f "${genimg_script_dir}/genimg.py" ]; then
    IMAGE_API_BASE="$genimg_base_url" \
    GENIMG_API_KEY="$genimg_api_key" \
    python3 "${genimg_script_dir}/genimg.py" \
        "banana/image2 配置检查" \
        --provider banana,image2 \
        --dry-run
fi

unset genimg_api_key
echo
echo "配置完成。"
echo "当前终端执行：source \"$genimg_env_file\""
echo "然后即可运行：python3 genimg.py \"一张测试图片\" --provider banana"
